full_rebuild: true

title: vlau.me
url: https://vlau.me
description: 'vlau.me is a searchable link collection for my fellow Computer Science and Media students at Bauhaus-Univerität Weimar.'

permalink: /:title

include:
  - '.htaccess'
  - '_data'

exclude:
  - 'node_modules'
  - '*.sublime-workspace'

gems:
  - jekyll-sitemap

kramdown:
  input: GFM
  auto_ids: false

sass:
  style: compressed



color:
  text: ffe0e7
  background: 28143d
  ui: 8f2400

author:
  mail: 'phrudloff@gmail.com'
  website: 'https://kleinfreund.de'

# compress.html by Anatol Broder (http://jch.penibelst.de)
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
  endings: all
#  ignore:
#    envs: [local]


defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "redirects"
    values:
      layout: "redirect"
